name: dio_logger_plus
description: >-
  A powerful and customizable Dio interceptor for Flutter that logs HTTP requests,
  responses, headers, and errors with pretty-printed JSON. Useful for debugging
  and development.

version: 1.2.1
homepage: https://github.com/AbbosbekBotirjonovich/dio_logger_plus.git

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ">=5.7.0 <6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - dio
  - http
  - logging
  - network
